apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger
spec:
  selector:
    matchLabels:
      app: ledger
  template:
    metadata:
      labels:
        app: ledger
    spec:
      containers:
      - name: ledger
        image: oluwasayo91/fintech-ledger
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Kubernetes"

---
apiVersion: v1
kind: Service
metadata:
  name: ledger-service
spec:
  type: ClusterIP
  selector:
    app: ledger
  ports:
  - port: 80
    targetPort: 8080

