<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Demo.Settlement-c6b55b8d-b055-47ae-b0bb-052d43c6405e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Demo.Common" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
  </ItemGroup>
</Project>
